[package]
name = "cosmic-applet-mare-fuzz"
version = "0.4.2"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.cosmic-applet-mare]
path = ".."
default-features = false

[[bin]]
name = "fuzz_lrc_parse"
path = "fuzz_targets/fuzz_lrc_parse.rs"
test = false
doc = false
bench = false
